### ISSUE TITLE
Installation issues on 5.19.0 Kernel 

### ISSUE THREAD

**Issue by VictoriaCreaser** [MichaelZaidman/hid-ft260#28]
Hello, are there any known issues with trying to install this driver on a 5.19.0 Kernel? I have used your driver on a 6.8.0-40 kernel on the same computer and it works perfectly. But I run into errors when I execute the Makefile on the 5.19.0. For example, there is an implicit declaration error on `timer_delete_sync()` and an incompatible pointer on `ft260_uart_set_termios()`. I have also tried compiling the hid-ft260.c without the Makefile and run into similar issues, where many of the types/declarations from the imported header files do not seem to be detected.

**Comment by MichaelZaidman** [comment]
Hi @VictoriaCreaser,

I assume you need the UART part since the FT260 I2C bus support is in the mainline starting from the 5.13 kernel.
The kernel infrastructure is evolving, and drivers are adapting to it. You may need to backport the driver to the kernel you'd like to use. Specifically, for the 5.19.0, the changes should be trivial:

For the implicit declaration error on timer_delete_sync(), please take a look at [timers: Rename del_timer_sync() to timer_delete_sync()](https://lore.kernel.org/lkml/166929936893.4906.6484824433900031971.tip-bot2@tip-bot2/) commit. To resolve the compilation error, rename the `timer_delete_sync` to `del_timer_sync`.

For the second issue, you may add `EXTRA_CFLAGS += -Wno-incompatible-pointer-types` to the Makefile or modify the pointer type in the code.

**Comment by VictoriaCreaser** [comment]
Thank you!
